version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Laravel Application Service
  app:
    container_name: laravel_app
    image: mo1074/multiauth:v1
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html


volumes:
  db_data:
