version: '3.1'

services:
  app:
    image: mo1074/multiauth:v1
    container_name: laravel-app
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=multiauth
      - DB_USERNAME=root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: multiauth
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
