apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1  # Specify the number of replicas
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mo1074/multiauth:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: svc-db
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: multiauth
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: root
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db  # Changed the name to avoid conflict
spec:
  replicas: 1  # Specify the number of replicas for the database
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root  # Set root password for MySQL
        volumeMounts:
          - name: v1
            mountPath: /var/lib/mysql
      volumes:
        - name: v1
          persistentVolumeClaim:
            claimName: v1

---
apiVersion: v1
kind: Service
metadata:
   name: svc-db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v1
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
